- name: Install python-pycurl and python-apt
  apt: pkg={{ item }} update_cache=yes state=present cache_valid_time=3600
  with_items:
   - python-pycurl
   - python-apt
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable Logstash repository
  apt_repository:
    repo: "deb http://packages.elasticsearch.org/logstash/{{ logstash_version }}/debian stable main"
    state: present

- name: Add Logstash repo key
  apt_key: url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install Logstash from repository
  apt: pkg={{ item }} update_cache=yes state=present allow_unauthenticated=yes cache_valid_time=3600
  with_items:
   - logstash
   - logstash-contrib
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- raw: sudo update-rc.d logstash defaults

- raw: sudo update-rc.d logstash enable
