---
- name: install haproxy
  apt: pkg={{ item }} state=present force=yes cache_valid_time=3600
  with_items:
      - haproxy
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Starting haproxy setup
  include: master.yml
  when: (ansible_hostname == "app-server-node-3") or
        (ansible_hostname == "app-server-node-4")
