---
- name: install apache webserver
  apt: 
    state: present 
    force: yes 
    cache_valid_time: 3600
    pkg: [
      apache2,
      apache2-doc,
    ]
    
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
