---
- name: install tomcat
  apt: pkg={{ item }} state=present force=yes cache_valid_time=3600
  with_items:
    - tomcat7
    - unzip
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2


- name: install default tomcat7 settings
  copy: src=default dest=/etc/default/tomcat7 force=yes mode=0644

- name: set default tomcat configuration
  copy: src=server.xml dest=/var/lib/tomcat7/conf/server.xml force=yes mode=0644

- name: copy default tomcat user config
  copy: src=tomcat-users.xml dest=/var/lib/tomcat7/conf/tomcat-users.xml force=yes mode=0644

- name: download psi probe
  become: true
  become_user: tomcat7
  get_url:
    url: https://github.com/psi-probe/psi-probe/releases/download/2.3.3/probe-2.3.3.zip
    dest: /tmp/probe-2.3.3.zip
    mode: 0644

- name: install psi probe
  raw: sudo unzip -o -C /tmp/probe-2.3.3.zip -d /var/lib/tomcat7/webapps/
  notify: restart tomcat7
